# Generated by Django 4.1.3 on 2022-11-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingbooks',
            name='comment',
            field=models.CharField(max_length=250),
        ),
    ]
